### ISSUE TITLE
Offset network is not learnt

### ISSUE THREAD

**Issue by minh-nguyenhoang** [giangbang/Pure-Pytorch-implementation-Deformable-Convolution#1]
Hi and thank you for a great implementation. It is very easy to understand the code and the flow of the operator. But there is a problem when it come to taking the offset index, that this is non-differentiable, so the offset network that generate those offset is not learnt during training. Will this cause any problem? Or does the original implementation of pytorch solve this problem?

**Comment by giangbang** [comment]
Hi @minh-nguyenhoang , thank you for being interested in the code.

Though I've never tested the gradient backward pass of this implementation before until today when you raised this issue. Here is the [colab notebook](https://colab.research.google.com/drive/1wWj8ZBvKm8QYODpV9a_NTtBf-UFN0Ddb?usp=sharing) demonstrating that the gradient calculated from this code and the pytorch cuda code are actually the same. I invite you to take a look at this code, you can also run it yourself.

Regarding your problem, I think maybe you can check if `offset` requires grad before passing through deformable?

Feel free to drop further questions here, if you have any.

**Comment by minh-nguyenhoang** [comment]
Thanks for the quick response. It's great to hear that your implementation is still able to differentiate wrt the offset. I will close this issue and investigate it again to understand how the offset is propagated.
